### ISSUE TITLE
出现一个图片外链至您的博客中加载

### ISSUE THREAD

**Issue by lioliy** [moumao/hexo-theme-Vateral#18]
主题的作者您好，非常喜欢这个主题
不过有点小问题向您反馈一下
在 source/css/main.min.css 文件中，出现了您的网址
![653ACDD4-98CC-43BB-A2A5-DC506B849A8C.png](https://ooo.0o0.ooo/2017/07/11/5964da4d1abc4.png)
看了下和source/images/link/all.png 文件一模一样，建议删除这条外链。

**Comment by lioliy** [comment]
另外搜索功能也用不了

**Comment by moumao** [comment]
谢谢反馈😀
